services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chuzone_db
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      - chuzone-net

  backend:
    build:
      context: ./apps/backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: database
      DB_NAME: chuzone_db
      DB_USER: root
      DB_PASSWORD: password
    depends_on:
      database:
        condition: service_healthy
    networks:
      - chuzone-net

  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chuzone-net

networks:
  chuzone-net:
    driver: bridge
