apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuzone-app
  namespace: examen-26
  labels:
    app: chuzone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chuzone-app
  template:
    metadata:
      labels:
        app: chuzone-app
    spec:
      containers:
      - name: chuzone-app
        image: mahdihemdane/chuzone-poc:1.0.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
