apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuzone-app
  namespace: examen-26
  labels:
    app: chuzone-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chuzone-app
  template:
    metadata:
      labels:
        app: chuzone-app
    spec:
      containers:
      - name: chuzone-app
        image: chuzone-poc:latest
        imagePullPolicy: Never
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: AWS_SESSION_TOKEN
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
