apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chuzone-ingress
  namespace: examen-26
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: chuzone.duckdns.org # Replace with your DuckDNS domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chuzone-service
            port:
              number: 80
