apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: examen-26
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "testing-key"
  AWS_SECRET_ACCESS_KEY: "testing-secret"
  AWS_SESSION_TOKEN: "testing-token"
