apiVersion: v1
kind: Service
metadata:
  name: chuzone-service
  namespace: examen-26
spec:
  selector:
    app: chuzone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30007
  type: NodePort
