apiVersion: v1
kind: Service
metadata:
  name: chuzone
  namespace: chuzone
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: chuzone
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chuzone
  namespace: chuzone
spec:
  selector:
    matchLabels:
      app: chuzone
  template:
    metadata:
      labels:
        app: chuzone
    spec:
      containers:
      - image: mahdihemdane/chuzone-frontend:1.0.0
        name: chuzone
        ports:
        - containerPort: 80
