apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chuzone-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/MahdiHemdane/projet-devops.git
    targetRevision: main
    path: k8s/full-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: examen-26
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
