name: Phase 2 - Release Approve

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  release-promotion:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Necessary for tagging
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Promote Docker Image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/chuzone-poc:1.0.0-RC1
        docker tag ${{ secrets.DOCKER_USERNAME }}/chuzone-poc:1.0.0-RC1 ${{ secrets.DOCKER_USERNAME }}/chuzone-poc:1.0.0
        docker push ${{ secrets.DOCKER_USERNAME }}/chuzone-poc:1.0.0
        
    - name: Create Git Tag
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git tag v1.0.0
        git push origin v1.0.0
